// Function: main @ 0x11c0
  int32_t main(int32_t argc, char** argv, char** envp)
{
    char* rax = strrchr(*argv, 0x2f);
    progname = rax;
    char* rdx = &rax[1];
    
    if (!rax)
        rdx = *argv;
    
    progname = rdx;
    uint64_t* const filename = nullptr;
    debug = 0;
    
    while (true)
    {
        int32_t rax_1 = getopt(argc, argv, "do:");
        
        if (rax_1 == 0xffffffff)
            break;
        
        if (rax_1 == 0x64)
            debug = 1;
        else
        {
            if (rax_1 != 0x6f)
            {
                uint64_t progname_1 = progname;
                __fprintf_chk(stderr, 1, "%s: usage: %s [-d] [-o filename]\n", progname_1, 
                    progname_1);
                exit(2);
                /* no return */
            }
            
            filename = optarg;
        }
    }
    
    FILE* fp;
    
    if (!filename)
        fp = stdout;
    else
    {
        FILE* fp_1 = fopen(filename, "w");
        fp = fp_1;
        
        if (!fp_1)
        {
            char* rax_31 = strerror(*__errno_location());
            __fprintf_chk(stderr, 1, "%s: %s: cannot open: %s\n", progname, filename, rax_31);
            exit(1);
            /* no return */
        }
    }
    
    int32_t* i_1 = &lsyntax;
    
    for (int32_t* i = &lsyntax; i != &data_404620; i = &i[1])
        *i = 0;
    
    sub_4018a0("()<>;&|", 1);
    sub_4018a0("()<>;&| \t\n", 2);
    sub_401820(0x60, 4);
    sub_4018a0(""`'", 8);
    sub_401820(1, 0x10);
    sub_401820(0x7f, 0x10);
    sub_4018a0("$<>", 0x20);
    sub_4018a0("\`$"\n", 0x40);
    sub_4018a0("\`$", 0x80);
    sub_4018a0("*?[]^", 0x100);
    sub_4018a0("@*+?!", 0x200);
    sub_4018a0(""`'", 0x400);
    sub_401820(0x5c, 0x400);
    sub_4018a0("@*#?-$!", 0x800);
    sub_4018a0("-=?+", 0x1000);
    uint16_t* rax_19 = *__ctype_b_loc();
    
    do
    {
        if (*rax_19 & 1)
            *i_1 |= 0x2000;
        
        i_1 = &i_1[1];
        rax_19 = &rax_19[1];
    } while (i_1 != &data_404620);
    
    __fprintf_chk(fp, 1, "%s\n", 
        "/*\n * This file was generated by mksyntax.  DO NOT EDIT.\n */\n\n");
    int64_t i_2 = 0;
    __fprintf_chk(fp, 1, "%s\n", "#include "config.h"\n#include "stdc.h"\n#include "syntax.h"\n\n");
    __fprintf_chk(fp, 1, "int sh_syntabsiz = %d;\n", 0x100);
    __fprintf_chk(fp, 1, "int sh_syntaxtab[%d] = {\n", 0x100);
    
    do
    {
        int32_t r13_1 = i_2;
        putc(9, fp);
        int32_t rcx_1 = 1;
        void* j = &data_4040b0;
        int32_t rbx_1 = *(&lsyntax + (i_2 << 2));
        
        if (rbx_1)
        {
            do
            {
                if (rbx_1 & *j)
                {
                    if (!rcx_1)
                        putc(0x7c, fp);
                    
                    fputs(*(j + 8), fp);
                    rcx_1 = 0;
                }
                
                j += 0x10;
            } while (j != &__bss_start);
        }
        else
            fputs(data_4040a8, fp);
        
        i_2 += 1;
        putc(0x2c, fp);
        fputs("\t\t/* ", fp);
        __fprintf_chk(fp, 1, "%s", sub_4016d0(r13_1));
        fputs(" */", fp);
        putc(0xa, fp);
    } while (i_2 != 0x100);
    
    __fprintf_chk(fp, 1, "};\n");
    
    if (stdout != fp)
        fclose(fp);
    
    exit(0);
    /* no return */
}

// Function: addcchar @ 0x1820
  int64_t addcchar(char arg1, int32_t arg2)
{
    uint64_t rbp = arg1;
    
    if (debug)
    {
        int32_t rax = 0;
        int32_t* rdx_1 = &wordflags;
        int64_t r12_1;
        
        while (true)
        {
            if (arg2 == *rdx_1)
            {
                r12_1 = (&data_4040a8)[rax * 2];
                break;
            }
            
            rax += 1;
            rdx_1 = &rdx_1[4];
            
            if (rax == 0xf)
            {
                r12_1 = 0;
                break;
            }
        }
        
        rbp = arg1;
        __fprintf_chk(stderr, 1, "added %s for character %s\n", r12_1, sub_4016d0(rbp));
    }
    
    *(&lsyntax + (rbp << 2)) |= arg2;
    return &lsyntax;
}

// Function: addcstr @ 0x18a0
  int64_t addcstr(char* arg1, int32_t arg2)
{
    char i = *arg1;
    
    if (!i)
        return i;
    
    char* r14 = arg1;
    
    do
    {
        uint32_t i_1 = i;
        
        if (debug)
        {
            int32_t* rdx_1 = &wordflags;
            int32_t rax_1 = 0;
            int64_t r12_1;
            
            while (true)
            {
                if (arg2 == *rdx_1)
                {
                    r12_1 = (&data_4040a8)[rax_1 * 2];
                    break;
                }
                
                rax_1 += 1;
                rdx_1 = &rdx_1[4];
                
                if (rax_1 == 0xf)
                {
                    r12_1 = 0;
                    break;
                }
            }
            
            __fprintf_chk(stderr, 1, "added %s for character %s\n", r12_1, sub_4016d0(i_1));
        }
        
        int64_t i_2 = i_1;
        r14 = &r14[1];
        *(&lsyntax + (i_2 << 2)) |= arg2;
        i = *r14;
    } while (i);
    
    return i;
}

